import Link from 'next/link';
import {requireProfile} from '@/lib/auth';
import {summarizeAnalytics,type AnalyticsLead,type AnalyticsCall,type AnalyticsMeeting} from '@/lib/analytics';
export default async function AnalyticsPage({searchParams}:{searchParams:Promise<{days?:string}>}){
 const {supabase,profile}=await requireProfile();const params=await searchParams;const days=['7','30','90'].includes(params.days??'')?Number(params.days):30;
 async function readAll(table:'lead_directory'|'calls'|'meetings',columns:string){
  const rows:unknown[]=[];
  for(let offset=0;offset<=50000;offset+=500){const {data,error}=await supabase.from(table).select(columns).order('id').range(offset,offset+499);if(error)throw new Error('Unable to load analytics. Please try again.');if(offset===50000&&data?.length)throw new Error('Analytics exceeds the current 50,000-record reporting limit. A database aggregation is needed.');rows.push(...(data??[]));if(!data||data.length<500)break;}
  return rows;
 }
 const [leads,calls,meetings,tasks]=await Promise.all([readAll('lead_directory','id,industry,status'),readAll('calls','id,lead_id,date,outcome'),readAll('meetings','id,lead_id,status'),supabase.from('tasks').select('id',{head:true,count:'exact'}).eq('status','pending')]);
 if(tasks.error)throw new Error('Unable to load follow-up totals.');
 const stats=summarizeAnalytics(leads as AnalyticsLead[],calls as AnalyticsCall[],meetings as AnalyticsMeeting[],days);
 const maxCalls=Math.max(1,...stats.daily.map(d=>d.count));
 return <><div className="page-heading"><div><span className="eyebrow">OUTREACH PERFORMANCE</span><h1>Analytics</h1><p className="muted">{profile.role==='admin'?'Workspace-wide':'Your assigned prospects'} · Current data, all-time totals.</p></div><Link className="button secondary" href="/calling">Open calling queue ↗</Link></div>
 <div className="analytics-kpis">{[['Total leads',stats.total],['Calls made',stats.calls],['Contacts reached',stats.reached],['Meetings booked',stats.meetingsBooked],['Lead-to-client conversion',stats.conversion.toFixed(1)+'%'],['Active follow-ups',tasks.count??0]].map(([label,value])=><section className="panel analytics-kpi" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div>
 <section className="panel analytics-section"><div className="section-heading"><h2>Calls per day</h2><form><label>Activity window <select name="days" defaultValue={days}>{[7,30,90].map(n=><option value={n} key={n}>Last {n} days</option>)}</select></label><button className="button secondary">Show</button></form></div><p className="muted">UTC · {stats.daily.reduce((sum,d)=>sum+d.count,0)} calls in this window. The totals above remain all-time.</p><div className="call-chart" role="img" aria-label={'Daily calls over the last '+days+' days. Exact values in the table below.'}>{stats.daily.map(day=><div className="chart-day" key={day.date} title={day.date+': '+day.count+' calls'}><span style={{height:(day.count/maxCalls*100)+'%'}}/><small>{day.date.slice(8)}</small></div>)}</div><details><summary>View daily call counts</summary><div className="table-wrap"><table><thead><tr><th>Date (UTC)</th><th>Calls</th></tr></thead><tbody>{stats.daily.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.count}</td></tr>)}</tbody></table></div></details></section>
 <section className="panel analytics-section"><h2>Prospect funnel</h2><p className="muted">Unique prospects by recorded milestones or current stage. Later stages imply earlier milestones; this is not a historical cohort conversion report.</p><div className="funnel">{stats.funnel.map(stage=><div key={stage.label}><span>{stage.label}</span><div className="funnel-track"><span style={{width:(stats.total?stage.count/stats.total*100:0)+'%'}}/></div><strong>{stage.count}</strong></div>)}</div></section>
 <section className="panel analytics-section"><h2>Industry performance</h2><p className="muted">Calls are attempts. Meeting prospects and clients are unique leads; repeated meetings do not inflate counts.</p><div className="table-wrap"><table><thead><tr><th>Industry</th><th>Leads</th><th>Calls</th><th>Meeting prospects</th><th>Clients</th><th>Lead-to-client</th></tr></thead><tbody>{stats.niches.map(n=><tr key={n.industry}><td>{n.industry}</td><td>{n.leads}</td><td>{n.calls}</td><td>{n.meetings}</td><td>{n.won}</td><td>{(n.won/n.leads*100).toFixed(1)}%</td></tr>)}</tbody></table></div>{!stats.niches.length&&<p className="muted">No leads yet. Import prospects to start measuring performance.</p>}</section>
 <details className="panel analytics-section"><summary>How these figures are calculated</summary><p>Contacts reached counts unique prospects with Interested, Follow-up, Meeting booked, or Not interested call outcomes. No answer and Wrong number do not count. Meetings booked counts non-cancelled meeting records, including completed meetings and no-shows. Meeting prospects in the funnel includes non-cancelled meeting records or a current Meeting scheduled, Demo, Trial, or Won stage. Conversion is currently Won leads divided by all visible leads. Active follow-ups counts pending tasks, including overdue tasks.</p><p>Only structured call records count as calls; free-text call activities do not contain reliable outcome data. Figures reflect your current access and assignments, not calls personally placed by you. No leads or meetings means zero, not a missing-data estimate.</p></details></>;
}

